; This file was automatically generated by ScriptHubImporter.py
this.ThelloraPlateausOfUnicornRunHandler.baseFavorExponent := New GameObjectStructure(this.ThelloraPlateausOfUnicornRunHandler,"Int", [0x90])
this.ThelloraPlateausOfUnicornRunHandler.controller := New GameObjectStructure(this.ThelloraPlateausOfUnicornRunHandler,"Int", [0x10])
this.ThelloraPlateausOfUnicornRunHandler.controller.userData := New GameObjectStructure(this.ThelloraPlateausOfUnicornRunHandler.controller,"Int", [0xc0])
this.ThelloraPlateausOfUnicornRunHandler.controller.userData.StatHandler := New GameObjectStructure(this.ThelloraPlateausOfUnicornRunHandler.controller.userData,"Int", [0x30])
this.ThelloraPlateausOfUnicornRunHandler.controller.userData.StatHandler.ServerStats := New GameObjectStructure(this.ThelloraPlateausOfUnicornRunHandler.controller.userData.StatHandler,"Dict", [0x78])
this.ThelloraPlateausOfUnicornRunHandler.controller.userData.StatHandler.ServerStats._CollectionKeyType := "System.String"
this.ThelloraPlateausOfUnicornRunHandler.controller.userData.StatHandler.ServerStats._CollectionValType := "Engine.Numeric.Quad"
